### ISSUE TITLE
Nixify Wezterm Config

### ISSUE THREAD

**Issue by dvogeldev** [kenranunderscore/dotfiles#2]
Thank you for sharing your dots. I noticed you're using the old school method for configuring you wezterm by referencing a wezterm.lua file. You might consider changing to something like this:

```
{ config, pkgs, ... }: {
  programs.wezterm = {
    enable = true;
    extraConfig = ''
      return {
        font = wezterm.font('Hasklug Nerd Font'),
        font_size = 24.0,
        enable_tab_bar = false,
        window_padding = {
          left = 5,
          right = 5,
          top = 5,
          bottom = 5
        },
        default_prog = { "fish", '-l' },
        color_scheme = "Catppuccin Mocha",
      }
    '';
  };
}
```

**Comment by kenranunderscore** [comment]
Hey, thanks for the heads-up!

Yeah, I've been doing this for most of the programs I use already, but I've gradually gone back to
- just using config files instead; they nearly always map better to the actual documentation and you never have to "break out" of the Nix DSL on top of it (in this case it won't matter much if at all, but in `zsh` for instance you have to understand exactly how the resulting config is created by Nix anyway if you want to achieve some special behavior, and then it gets really ugly).
- mutable configuration: in programs like Emacs (even though I can evaluate things at runtime) where I iterate a lot over my configuration it gets tedious quickly to have to `nixos-rebuild` (or even create a new `home-manager` generation) in order to be able to try out things properly.

I don't know if I'm even going to use `wezterm` any longer, but if I do, I will surely end up with a mutable config for the reasons above, as it also supports hot reloading of this file. Version controlled configuration is enough for me in this case :)

Of course, there are cases where I still prefer the Nix configuration, for instance with `accounts.*`, `ssh` etc. :)
